// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "mainnet"
    static let defaultNodeURL = "https://rpc.tari.com"
    static let isTestnet = false
    /// Whether Ootle (Tari's layer 2) runs on this network yet. If not, the TARI side is a preview.
    static let ootleAvailable = false
    static let ootleNetwork = "mainnet"
    static let ootleIndexerURL = ""
    static let ootleAddressPrefix = "otl_1"
}
