// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "esmeralda"
    static let defaultNodeURL = "https://rpc.esmeralda.tari.com"
    static let isTestnet = true
    /// Whether Ootle (Tari's layer 2) runs on this network yet. If not, the TARI side is a preview.
    static let ootleAvailable = true
    static let ootleNetwork = "esmeralda"
    static let ootleIndexerURL = "https://ootle-indexer-a.tari.com/"
    static let ootleAddressPrefix = "otl_esm_1"
}
