#!/bin/bash
# Builds Clew's wallet library (rust/clew-core: Tari's wallet library plus the Ootle wallet) for
# Apple Silicon Macs and copies it, with its C headers, into Frameworks/TariFFI where Xcode picks
# it up.
#
# Usage: scripts/build-ffi.sh [esme|mainnet]   (default: esme = testnet)
set -euo pipefail

NETWORK="${1:-esme}"
TARI_TAG="v6.1.0"
OOTLE_TAG="v0.45.0"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARI="$ROOT/vendor/tari"
OOTLE="$ROOT/vendor/tari-ootle"
CORE="$ROOT/rust/clew-core"
OUT="$ROOT/Frameworks/TariFFI"

case "$NETWORK" in
  esme)
    export TARI_NETWORK=esme TARI_TARGET_NETWORK=testnet TARI_NETWORK_DIR=testnet
    APP_NETWORK=esmeralda NODE_URL=https://rpc.esmeralda.tari.com IS_TESTNET=true ;;
  mainnet)
    export TARI_NETWORK=mainnet TARI_TARGET_NETWORK=mainnet TARI_NETWORK_DIR=mainnet
    APP_NETWORK=mainnet NODE_URL=https://rpc.tari.com IS_TESTNET=false ;;
  *) echo "unknown network: $NETWORK" >&2; exit 1 ;;
esac

# Refuse to build from anything other than the pinned releases, then apply Clew's changes once:
# Tari gets Tor proxy support and no silent fallback node, Ootle gets Tor proxy support.
use_release() { # folder tag patch
  local actual
  actual="$(git -C "$1" describe --tags --exact-match 2>/dev/null || true)"
  if [ "$actual" != "$2" ]; then
    echo "${1#$ROOT/} is at '${actual:-untagged}', expected $2" >&2
    exit 1
  fi
  if git -C "$1" apply --reverse --check "$3" 2>/dev/null; then
    echo "Clew patch already applied to ${1#$ROOT/}"
  else
    git -C "$1" apply -N "$3"   # -N: new files show up in git diff
    echo "Applied ${3#$ROOT/}"
  fi
}
use_release "$TARI" "$TARI_TAG" "$ROOT/patches/tari-$TARI_TAG-clew.patch"
use_release "$OOTLE" "$OOTLE_TAG" "$ROOT/patches/tari-ootle-$OOTLE_TAG-clew.patch"
# The Tari patch adds a dependency between two Tari crates. Record just that in Tari's Cargo.lock
# (no outside crate changes version); it is what generates wallet.h below.
cargo update --manifest-path "$TARI/Cargo.toml" --workspace --offline --quiet
# Regenerate wallet.h from the current source (the generator only reruns when build.rs changes).
touch "$TARI/base_layer/wallet_ffi/build.rs"

export MACOSX_DEPLOYMENT_TARGET=14.0
# clew-core's own Cargo.lock pins every outside crate; build strictly from it.
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/build/clew-core-target}"
CARGO_TARGET_DIR="$TARGET_DIR" cargo build --manifest-path "$CORE/Cargo.toml" --release --locked \
  --target aarch64-apple-darwin

mkdir -p "$OUT"
rm -f "$OUT/libminotari_wallet_ffi.a"
cp "$TARGET_DIR/aarch64-apple-darwin/release/libclew_core.a" "$OUT/"
cp "$TARI/base_layer/wallet_ffi/wallet.h" "$CORE/include/clew_ootle.h" "$OUT/"
echo "$NETWORK tari $TARI_TAG $(git -C "$TARI" rev-parse --short HEAD), ootle $OOTLE_TAG $(git -C "$OOTLE" rev-parse --short HEAD)" \
  > "$OUT/BUILD_INFO"

# The app's network settings must match the library, so generate them here.
cat > "$ROOT/Clew/App/Config.swift" <<EOF
// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "$APP_NETWORK"
    static let defaultNodeURL = "$NODE_URL"
    static let isTestnet = $IS_TESTNET
}
EOF
echo "Built $NETWORK wallet library -> $OUT"
