#!/bin/bash
# Builds Clew's wallet library (rust/clew-core: Tari's wallet library plus the Ootle wallet) for
# Apple Silicon Macs, with its C headers, where Xcode picks it up. Tari builds its library for one
# network family, so there are two: mainnet for Clew (Frameworks/TariFFI) and testnet for Clew
# Testnet (Frameworks/TariFFI-testnet). Each also gets the app's network settings (Config/).
#
# Usage: scripts/build-ffi.sh [mainnet|esme]   (default: both)
set -euo pipefail

if [ $# -eq 0 ]; then
  "$0" mainnet
  exec "$0" esme
fi
NETWORK="$1"
TARI_TAG="v6.1.0"
TARI_COMMIT="463e53d372ce296b2eb1853b9b53d1ab77e1bc87"
OOTLE_TAG="v0.45.0"
OOTLE_COMMIT="9c626062673760530ffb075b6b006a67becebe5a"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARI="$ROOT/vendor/tari"
OOTLE="$ROOT/vendor/tari-ootle"
CORE="$ROOT/rust/clew-core"

case "$NETWORK" in
  esme)
    export TARI_NETWORK=esme TARI_TARGET_NETWORK=testnet TARI_NETWORK_DIR=testnet
    APP_NETWORK=esmeralda NODE_URL=https://rpc.esmeralda.tari.com IS_TESTNET=true
    OOTLE_AVAILABLE=true OOTLE_NETWORK=esmeralda OOTLE_INDEXER=https://ootle-indexer-a.tari.com/ OOTLE_PREFIX=otl_esm_1
    OUT="$ROOT/Frameworks/TariFFI-testnet" CONFIG="$ROOT/Config/Testnet/Config.swift" ;;
  mainnet)
    export TARI_NETWORK=mainnet TARI_TARGET_NETWORK=mainnet TARI_NETWORK_DIR=mainnet
    APP_NETWORK=mainnet NODE_URL=https://rpc.tari.com IS_TESTNET=false
    # Ootle has no mainnet yet (no indexer to talk to), so Clew shows its TARI side as a preview.
    OOTLE_AVAILABLE=false OOTLE_NETWORK=mainnet OOTLE_INDEXER= OOTLE_PREFIX=otl_1
    OUT="$ROOT/Frameworks/TariFFI" CONFIG="$ROOT/Config/Mainnet/Config.swift" ;;
  *) echo "unknown network: $NETWORK" >&2; exit 1 ;;
esac

# Refuse to build from anything other than the pinned releases (by commit, since a tag can be moved),
# then apply Clew's changes once: Tari gets Tor proxy support and no silent fallback node, Ootle gets
# Tor proxy support.
use_release() { # folder tag commit patch
  local actual
  actual="$(git -C "$1" rev-parse HEAD 2>/dev/null || true)"
  if [ "$actual" != "$3" ]; then
    echo "${1#$ROOT/} is at '${actual:-nothing}', expected $2 ($3)" >&2
    exit 1
  fi
  if git -C "$1" apply --reverse --check "$4" 2>/dev/null; then
    echo "Clew patch already applied to ${1#$ROOT/}"
  else
    git -C "$1" apply -N "$4"   # -N: new files show up in git diff
    echo "Applied ${4#$ROOT/}"
  fi
}
use_release "$TARI" "$TARI_TAG" "$TARI_COMMIT" "$ROOT/patches/tari-$TARI_TAG-clew.patch"
use_release "$OOTLE" "$OOTLE_TAG" "$OOTLE_COMMIT" "$ROOT/patches/tari-ootle-$OOTLE_TAG-clew.patch"
# The Tari patch adds a dependency between two Tari crates. Record just that in Tari's Cargo.lock
# (no outside crate changes version); it is what generates wallet.h below.
cargo update --manifest-path "$TARI/Cargo.toml" --workspace --offline --quiet
# Regenerate wallet.h from the current source (the generator only reruns when build.rs changes).
touch "$TARI/base_layer/wallet_ffi/build.rs"

export MACOSX_DEPLOYMENT_TARGET=14.0
# clew-core's own Cargo.lock pins every outside crate; build strictly from it.
# One target folder per network: the network is compiled in, so sharing one would rebuild everything
# each time.
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/build/clew-core-target-$NETWORK}"
CARGO_TARGET_DIR="$TARGET_DIR" cargo build --manifest-path "$CORE/Cargo.toml" --release --locked \
  --target aarch64-apple-darwin

mkdir -p "$OUT"
rm -f "$OUT/libminotari_wallet_ffi.a"
cp "$TARGET_DIR/aarch64-apple-darwin/release/libclew_core.a" "$OUT/"
cp "$TARI/base_layer/wallet_ffi/wallet.h" "$CORE/include/clew_ootle.h" "$OUT/"
cat > "$OUT/module.modulemap" <<EOF
module TariFFI {
    header "wallet.h"
    header "clew_ootle.h"
    link "clew_core"
    export *
}
EOF
echo "$NETWORK tari $TARI_TAG $(git -C "$TARI" rev-parse --short HEAD), ootle $OOTLE_TAG $(git -C "$OOTLE" rev-parse --short HEAD)" \
  > "$OUT/BUILD_INFO"

# The app's network settings must match the library, so generate them here.
mkdir -p "$(dirname "$CONFIG")"
cat > "$CONFIG" <<EOF
// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "$APP_NETWORK"
    static let defaultNodeURL = "$NODE_URL"
    static let isTestnet = $IS_TESTNET
    /// Whether Ootle (Tari's layer 2) runs on this network yet. If not, the TARI side is a preview.
    static let ootleAvailable = $OOTLE_AVAILABLE
    static let ootleNetwork = "$OOTLE_NETWORK"
    static let ootleIndexerURL = "$OOTLE_INDEXER"
    static let ootleAddressPrefix = "$OOTLE_PREFIX"
}
EOF
echo "Built $NETWORK wallet library -> $OUT"
