#!/bin/bash
# Builds the Tari wallet library (libminotari_wallet_ffi) for Apple Silicon Macs
# and copies it, with its C header, into Frameworks/TariFFI where Xcode picks it up.
#
# Usage: scripts/build-ffi.sh [esme|mainnet]   (default: esme = testnet)
set -euo pipefail

NETWORK="${1:-esme}"
TARI_TAG="v6.1.0"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARI="$ROOT/vendor/tari"
OUT="$ROOT/Frameworks/TariFFI"

case "$NETWORK" in
  esme)
    export TARI_NETWORK=esme TARI_TARGET_NETWORK=testnet TARI_NETWORK_DIR=testnet
    APP_NETWORK=esmeralda NODE_URL=https://rpc.esmeralda.tari.com IS_TESTNET=true ;;
  mainnet)
    export TARI_NETWORK=mainnet TARI_TARGET_NETWORK=mainnet TARI_NETWORK_DIR=mainnet
    APP_NETWORK=mainnet NODE_URL=https://rpc.tari.com IS_TESTNET=false ;;
  *) echo "unknown network: $NETWORK" >&2; exit 1 ;;
esac

# Refuse to build from anything other than the pinned release.
actual="$(git -C "$TARI" describe --tags --exact-match 2>/dev/null || true)"
if [ "$actual" != "$TARI_TAG" ]; then
  echo "vendor/tari is at '${actual:-untagged}', expected $TARI_TAG" >&2
  exit 1
fi

# Clew's changes to Tari (Tor proxy support, no silent fallback node). Applied once.
PATCH="$ROOT/patches/tari-$TARI_TAG-clew.patch"
if git -C "$TARI" apply --reverse --check "$PATCH" 2>/dev/null; then
  echo "Clew patch already applied"
else
  git -C "$TARI" apply "$PATCH"
  echo "Applied $PATCH"
fi
# The patch adds a dependency between two Tari crates. Record just that in Cargo.lock (no outside
# crate changes version), then build strictly from the lockfile.
cargo update --manifest-path "$TARI/Cargo.toml" --workspace --offline --quiet
# Regenerate wallet.h from the current source (the generator only reruns when build.rs changes).
touch "$TARI/base_layer/wallet_ffi/build.rs"

export MACOSX_DEPLOYMENT_TARGET=14.0
cargo build --manifest-path "$TARI/Cargo.toml" --release --locked \
  -p minotari_wallet_ffi --target aarch64-apple-darwin

mkdir -p "$OUT"
cp "${CARGO_TARGET_DIR:-$TARI/target}/aarch64-apple-darwin/release/libminotari_wallet_ffi.a" "$OUT/"
cp "$TARI/base_layer/wallet_ffi/wallet.h" "$OUT/"
echo "$NETWORK $TARI_TAG $(git -C "$TARI" rev-parse --short HEAD)" > "$OUT/BUILD_INFO"

# The app's network settings must match the library, so generate them here.
cat > "$ROOT/Clew/App/Config.swift" <<EOF
// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "$APP_NETWORK"
    static let defaultNodeURL = "$NODE_URL"
    static let isTestnet = $IS_TESTNET
}
EOF
echo "Built $NETWORK wallet library -> $OUT"
