// Generated by scripts/build-ffi.sh to match the bundled wallet library. Do not edit.
enum Config {
    static let network = "mainnet"
    static let defaultNodeURL = "https://rpc.tari.com"
    static let isTestnet = false
}
